-keep public class org.orynnx.outerview.core.** { public protected *; }
-keep class org.orynnx.outerview.core.ai.IAiAppHostService** { *; }
-keep class org.orynnx.outerview.core.ai.IAiAppHostConnection** { *; }
