-keep public class org.orynnx.outerview.core.** { public protected *; }
-keep class org.orynnx.outerview.core.hostapi.IFunCardHostService** { *; }
-keep class org.orynnx.outerview.core.hostapi.IFunCardHostConnection** { *; }
